### PR TITLE
add safeguard when link_text is empty

### PR DESCRIPTION
**Pull request by joans**

### CODE REVIEW

**Comment by joshy** [comment]
hey thanks, after my vacations I can merge the changes.

**Comment by joshy** [comment]
Could you maybe provide a test case as well?

**Comment by stevengj** [comment]
Why can't you simply end the hyperlink regex with `\}{2,3}` in order to match `}}` or `}}}`?

**Comment by joshy** [comment]
I tried but it never worked.--Sent from phoneOn 2 Jul 2023, at 22:26, Steven G. Johnson ***@***.***> wrote:﻿
Why can't you simply end the hyperlink regex with \}{2,3} in order to match }} or }}}?

**Comment by joans** [comment]
> I tried but it never worked. Why can't you simply end the hyperlink regex with \}{2,3} in order to match }} or }}}? 

Hey! I found out what the error was and submitted a proper fix for it. The regex would also match a line break character and the third group of the matches would contain said line break character, then as an empty string. I now modified the regex so it specifically does **not** match the line break character.

**Comment by stevengj** [comment]
> I tried [ending the hyperlink regex with `\}{2,3}`] but it never worked.

In the [Julia port my regex](https://github.com/JuliaStrings/StripRTF.jl/blob/d7a5edbecc23bbb37458729ca04139ddb41a36b9/src/StripRTF.jl#L90C1-L90C106) is:
```jl
const HYPERLINKS = r"(\{\\field\{\s*\\\*\\fldinst\{.*?HYPERLINK\s(\".*?\")\}{2}\s*\{.*?\s+(.*?)\}{2,3})"i
```
and the `{2,3}` at the end works fine to match `}}` or `}}}` — it passes all of your tests.  So I omitted the special `_is_hyperlink` "ugly hack" entirely.   I didn't the `\n` filtering by @joans either.

Am I missing something?  Or do Julia's regular expression semantics (from the PCRE library) differ from Python's somehow?

**Comment by joshy** [comment]
Hi Steven, thanks for the notice. I just made the change to use your regex to get rid of the "ugly hack".

**Pull request merged**
